/**
 * created by zhongxiaolong on 2020/02/06
 * 社区调查问卷-行程信息
 */
import TYPES from '../mutations-types'
import SERVICES from '../../services'
import BaseConstant from '../../constant/BaseConstant'
import { SMART_ORDER_API } from '../../services/apis'
import { API_GATEWAY } from '@/config/index.js'
import i18n from '@/i18n'

const state = {
  dict:{},
  name: '',
  title: i18n.t('MENU.TRAVEL_INFO'),
  view: 'TravelInformation',
  url: "",
  mate: {
    mateSearch: { // 本地配置查询配置
      multipleConditions: true, // 是否多条件查询
      fields: [
        {holder: "text", name: "dept2", label: "部门", lg: 4, md: 6, placeholder: "请填写部门", sm: 8},
        {holder: "text", name: "userNo", label: "工号", lg: 4, md: 6, placeholder: "请填写工号", sm: 8},
        {holder: "text", name: "uName", label: "姓名", lg: 4, md: 6, placeholder: "请填写姓名", sm: 8}
      ],
      values:{
        dept2: "",  // 部门
        userNo: "", // 工号
        uName: ""   // 姓名
      },
      url: `${API_GATEWAY}/question/app/report/personal/itinerary/list` // 查询/分页接口
    },
    mateList: {
      dataApi: '',
      size: 10,
      page: 1,
      total: 0,
      
      actions:[ 
        {action: "details",
          url: "",
          label: "查看",
          isApi: true,
          useId: 0,
          method: "GET",
          type: ""
        }
      ],
      btns: [
        {action: "refresh",label: "刷新列表",isApi: false,useId: -1,url: '',icon: "el-icon-refresh-right"},
        {action: "exportReport",label: "导出",isApi: false,useId: -1,url: '',icon: "el-icon-download"},
      ],
      columns: [
        // 基础信息
        {name: "USERNO", label: "工号", width: 100, isShow: true },
        {name: "UNAME", label: "姓名", width: 80, isShow: true },
        {name: "PERSONAL_CATEGORY", label: "人员类别", width: 80, isShow: true },
        {name: "DEPT1", label: "公司", width: 180, isShow: true },
        {name: "DEPT2", label: "部门", width: 180, isShow: true },
        {name: "GZDD", label: "工作地", width: 180, isShow: true },
        {name: "GZDDTYPE", label: "工作地类型", width: 180, isShow: true },
        {name: "NLSHENG", label: "出生籍贯省", width: 180, isShow: true },
        {name: "NLSHI", label: "出生籍贯市", width: 180, isShow: true },
        {name: "IDCARDDZ", label: "身份证地址", width: 100, isShow: true },
        {name: "INFO5", label: "工作地住房类型", width: 150, isShow: true },
        {name: "INFO1G1", label: "工作地住房地址", width: 150, isShow: true },
        {name: "INFO5G1", label: "住房详细地址", width: 120, isShow: true },
        {name: "LEAD_NAME", label: "直接领导姓名", width: 150, isShow: true },
        {name: "LEAD_TEL", label: "直接领导联系方式", width: 170, isShow: true },
        {name: "INFO6", label: "上下班交通", width: 120, isShow: true },
        {name: "INFO6G1", label: "上下班交通说明", width: 120, isShow: true },
        {name: "INFO1", label: "婚姻状况", width: 100, isShow: true },
        // 返工情况
        {name: "IS_BACK", label: "是否返回工作地", width: 120, isShow: true },
        {name: "BACK_DATE", label: "计划返回时间", width: 120, isShow: true },
        {name: "BACK_TRAFFIC", label: "返程交通工具", width: 120, isShow: true },
        {name: "BACK_TRAFFIC_INFO", label: "具体车次_航班号", width: 130, isShow: true },
        {name: "CAN_WORK", label: "是否正常复工", width: 120, isShow: true },
        {name: "CANNOT_CREASON", label: "不能复工原因", width: 120, isShow: true },
        {name: "PLAN_WORK_DATE", label: "计划上班日期", width: 120, isShow: true },
        {name: "IS_KNOW_RULE", label: "清楚公司复工要求", width: 150, isShow: true },
        {name: "IS_LEADER_CONTACT", label: "领导是否有联系", width: 120, isShow: true },
        {name: "IS_LEADER_CONTACT_LAST_DATE", label: "最近一次联系", width: 120, isShow: true },
        {name: "IS_LEADER_CONTACT_COUNT", label: "联系过几次", width: 100, isShow: true },
        {name: "QUESTION", label: "面临最大问题", width: 110, isShow: true },
        // 家庭信息
        {name: "INFO1G2", label: "配偶籍贯", width: 80, isShow: true },
        {name: "INFO1G3", label: "配偶联系电话", width: 120, isShow: true },
        {name: "INFO2", label: "父是否建在", width: 100, isShow: true },
        {name: "INFO2G1", label: "父姓名", width: 80, isShow: true },
        {name: "INFO2G2", label: "父年龄", width: 80, isShow: true },
        {name: "INFO2G3", label: "父籍贯", width: 80, isShow: true },
        {name: "INFO2G4", label: "父工作地", width: 100, isShow: true },
        {name: "INFO2G5", label: "父居住地", width: 150, isShow: true },
        {name: "INFO2G6", label: "父联系电话", width: 100, isShow: true },
        {name: "INFO3", label: "母是否建在", width: 100, isShow: true },
        {name: "INFO3G1", label: "母姓名", width: 80, isShow: true },
        {name: "INFO3G2", label: "母年龄", width: 80, isShow: true },
        {name: "INFO3G3", label: "母籍贯", width: 80, isShow: true },
        {name: "INFO3G4", label: "母工作地", width: 150, isShow: true },
        {name: "INFO3G5", label: "母居住地", width: 150, isShow: true },
        {name: "INFO3G6", label: "母联系电话", width: 100, isShow: true },
        {name: "INFO4G5", label: "子女居住地", width: 150, isShow: true },
        {name: "INFO4G6", label: "子女联系电话", width: 120, isShow: true },
        {name: "TEL", label: "电话", width: 80, isShow: true },
        {name: "KZ1", label: "内外人员标识", width: 130, isShow: true },
        {name: "SMOTHER_STATE", label: "配偶父親狀態", width: 120, isShow: true },
        {name: "SFATHER_STATE", label: "配偶母親狀態", width: 120, isShow: true },
        {name: "PERSON_COMPANY", label: "所属公司名称", width: 150, isShow: true },
        {name: "PERSON_I_D_CARD", label: "身份证号", width: 120, isShow: true },
        {name: "PERSON_COME_REASON", label: "来访事由", width: 100, isShow: true },
        {name: "PERSON_KZ", label: "按要求佩戴口罩", width: 120, isShow: true },
        {name: "PERSON_LEARN", label: "发文及相关规则", width: 130, isShow: true },
        {name: "INFO4", label: "子女状况", width: 80, isShow: true },
        {name: "INFO4G2", label: "子女出生年月", width: 120, isShow: true },
        {name: "INFO4G3", label: "子女性别", width: 100, isShow: true },
        {name: "INFO4G4", label: "子女学校或工作地", width: 140, isShow: true },
        {name: "KZ2", label: "N95口罩及数量", width: 120, isShow: true },
        {name: "KZ3", label: "其它口罩及数量", width: 120, isShow: true },
        {name: "IS_F_RETIRE", label: "父亲是否退休", width: 120, isShow: true },
        {name: "IS_M_RETIRE", label: "母亲是否退休", width: 120, isShow: true },
        {name: "SPOUSE_NAME", label: "配偶姓名", width: 100, isShow: true },
        {name: "SPOUSE_AGE", label: "配偶年龄", width: 150, isShow: true },
        {name: "SPOUSE_NATIVE", label: "配偶籍贯", width: 80, isShow: true },
        {name: "SPOUSE_ADDRESS", label: "配偶身份证地址", width: 150, isShow: true },
        {name: "SPOUSE_WORK", label: "配偶工作情况", width: 120, isShow: true },
        {name: "SPOUSEWORK_COMPANY", label: "配偶工作公司名称", width: 150, isShow: true },
        {name: "SPOUSEWORK_ADDRESS", label: "配偶工作地址", width: 130, isShow: true },
        {name: "SFATHER_NAME", label: "配偶父亲姓名", width: 120, isShow: true },
        {name: "SFATHER_AGE", label: "配偶父亲年龄", width: 120, isShow: true },
        {name: "SFATHER_ADDRESS", label: "配偶父亲居籍贯", width: 120, isShow: true },
        {name: "SFATHER_WORK_PLACE", label: "配偶父亲工作地", width: 120, isShow: true },
        {name: "SFATHER_LIVE_PLACE", label: "配偶父亲居住地", width: 120, isShow: true },
        {name: "SFATHER_TEL", label: "配偶父亲电话", width: 120, isShow: true },
        {name: "SIS_F_RETIRE", label: "配偶父亲是否退休", width: 150, isShow: true },
        {name: "SMOTHER_NAME", label: "配偶母亲姓名", width: 120, isShow: true },
        {name: "SMOTHER_AGE", label: "配偶母亲年龄", width: 120, isShow: true },
        {name: "SMOTHER_ADDRESS", label: "配偶母亲地址", width: 150, isShow: true },
        {name: "SMOTHER_WORK_PLACE", label: "配偶母亲工作地", width: 120, isShow: true },
        {name: "SMOTHER_LIVE_PLACE", label: "配偶母亲居住地", width: 120, isShow: true },
        {name: "SMOTHER_TEL", label: "配偶母亲电话", width: 120, isShow: true },
        {name: "SIS_M_RETIRE", label: "配偶母亲是否退休", width: 130, isShow: true },
        {name: "NAME5", label: "子女学习_工作情况", width: 140, isShow: true },
        // 行程信息
        {name: "SEL_TIME", label: "行程日期", width: 120, isShow: true },
        {name: "TI_WEN", label: "小区是否病例", width: 120, isShow: true },
        {name: "AREA", label: "区域", width: 100, isShow: true },
        {name: "LOC", label: "定位地址", width: 100, isShow: true },
        {name: "LEAVE_DATE", label: "离厂时间", width: 100, isShow: true },
        {name: "MODULE", label: "行程起始地点", width: 120, isShow: true },
        {name: "ADCODE", label: "行程结束地址", width: 120, isShow: true },
        {name: "TYPE", label: "类型", width: 80, isShow: true },
        {name: "DWELL1", label: "居住所在地省", width: 120, isShow: true },
        {name: "DWELL2", label: "居住所在地市", width: 120, isShow: true },
        {name: "DWELL3", label: "居住所在地区", width: 120, isShow: true },
        {name: "DWELL4", label: "地址", width: 80, isShow: true },
        {name: "REDIO1", label: "居住房类型", width: 120, isShow: true },
        {name: "REDIO1G", label: "其他", width: 80, isShow: true },
        {name: "REDIO2", label: "地区是否为疫区", width: 130, isShow: true },
        {name: "REDIO2G", label: "人数", width: 80, isShow: true },
        {name: "REDIO3", label: "当日自己身体状况", width: 150, isShow: true },
        {name: "REDIO3G", label: "当日自己身体说明", width: 150, isShow: true },
        {name: "REDIO4", label: "当日测量体温", width: 120, isShow: true },
        {name: "REDIO4G", label: "体温", width: 80, isShow: true },
        {name: "REDIO5", label: "是否有外出", width: 120, isShow: true },
        {name: "REDIO5G", label: "外出事项", width: 100, isShow: true },
        {name: "REDIO5G1", label: "外出地点", width: 80, isShow: true },
        {name: "REDIO5G2", label: "外出使用交通", width: 120, isShow: true },
        {name: "REDIO6", label: "聚会情况", width: 80, isShow: true },
        {name: "REDIO6G", label: "参加10人以上聚会", width: 150, isShow: true },
        {name: "REDIO6G1", label: "聚会地点", width: 100, isShow: true },
        {name: "REDIO6G2", label: "聚会类别", width: 100, isShow: true },
        {name: "REDIO7", label: "接触湖北人员", width: 120, isShow: true },
        {name: "REDIO7G", label: "接触湖北人员说明", width: 150, isShow: true },
        {name: "REDIO8", label: "车辆借出情况", width: 120, isShow: true },
        {name: "REDIO8G", label: "借出说明", width: 80, isShow: true },
        {name: "REDIO9", label: "接触高风险人群", width: 120, isShow: true },
        {name: "REDIO9G", label: "接触说明", width: 80, isShow: true },
        {name: "REDIO10", label: "当日居住", width: 80, isShow: true },
        {name: "REDIO10G", label: "当日居住说明", width: 120, isShow: true },
        {name: "REDIO11", label: "接待来访亲友", width: 120, isShow: true },
        {name: "REDIO11G", label: "亲友情况说明", width: 120, isShow: true },
        {name: "REDIO12", label: "接触人群状态", width: 120, isShow: true },
        {name: "REDIO12G", label: "接触人群情况说明", width: 150, isShow: true },
        {name: "REDIO13", label: "当日用餐情况", width: 120, isShow: true },
        {name: "REDIO13G", label: "用餐情况说明", width: 120, isShow: true },
        {name: "D_AREA", label: "是否到过重点疫情区域", width: 160, isShow: true },
        {name: "D_ISOLATE", label: "是否居家隔离", width: 130, isShow: true },
        {name: "DISO_CLATE_DAY", label: "居家隔离天数", width: 120, isShow: true },
        {name: "D_IS_INFECT", label: "小区病例情况", width: 120, isShow: true },
        {name: "ADD_TIME", label: "新增时间", width: 100, isShow: true },
        {name: "D_HIGH_PLACE", label: "到过以下高风险场所", width: 150, isShow: true },
        {name: "D_WEAR_MASK", label: "是否戴口罩", width: 100, isShow: true },
        {name: "BKZ1", label: "自有外科口罩数量", width: 150, isShow: true },
        {name: "BKZ2", label: "N95口罩及数量", width: 120, isShow: true },
        {name: "BKZ3", label: "其它口罩及数量", width: 120, isShow: true },
        {name: "STORK_DYNAMIC", label: "与领导沟通过本人行程", width: 160, isShow: true },
        {name: "D_HEALTH_FAMILY", label: "当日家人身体状况", width: 130, isShow: true },
        {name: "D_AREA_STATUS", label: "出行期间所去区域", width: 130, isShow: true },

       ],
      rows: []
    },
    mateFormerHeader: {
      labelWidth: "130px",
      fields: [
        { holder: "textc", name: "USERNO", label: "工号" },
        { holder: "textc", name: "UNAME", label: "姓名" },
        { holder: "textc", name: "PERSONAL_CATEGORY", label: "人员类别" },
        { holder: "textc", name: "DEPT1", label: "公司" },
        { holder: "textc", name: "DEPT2", label: "部门" },
        { holder: "textc", name: "GZDD", label: "工作地" },
        { holder: "textc", name: "GZDDTYPE", label: "工作地类型" },
        { holder: "textc", name: "NLSHENG", label: "出生籍贯省" },
        { holder: "textc", name: "NLSHI", label: "出生籍贯市" },
        { holder: "textc", name: "IDCARDDZ", label: "身份证地址" },
        { holder: "textc", name: "INFO5", label: "工作地住房类型" },
        { holder: "textc", name: "INFO1G1", label: "工作地住房地址" },
        { holder: "textc", name: "INFO5G1", label: "住房详细地址" },
        { holder: "textc", name: "LEAD_NAME", label: "直接领导姓名" },
        { holder: "textc", name: "LEAD_TEL", label: "直接领导联系方式" },
        { holder: "textc", name: "INFO6", label: "上下班交通" },
        { holder: "textc", name: "INFO6G1", label: "上下班交通说明" },
        { holder: "textc", name: "INFO1", label: "婚姻状况" },
        { holder: "textc", name: "IS_BACK", label: "是否返回工作地" },
        { holder: "textc", name: "BACK_DATE", label: "计划返回时间" },
        { holder: "textc", name: "BACK_TRAFFIC", label: "返程交通工具" },
        { holder: "textc", name: "BACK_TRAFFIC_INFO", label: "具体车次_航班号" },
        { holder: "textc", name: "CAN_WORK", label: "是否正常复工" },
        { holder: "textc", name: "CANNOT_CREASON", label: "不能复工原因" },
        { holder: "textc", name: "PLAN_WORK_DATE", label: "计划上班日期" },
        { holder: "textc", name: "IS_KNOW_RULE", label: "清楚公司复工要求" },
        { holder: "textc", name: "IS_LEADER_CONTACT", label: "领导是否有联系" },
        { holder: "textc", name: "IS_LEADER_CONTACT_LAST_DATE", label: "最近一次联系" },
        { holder: "textc", name: "IS_LEADER_CONTACT_COUNT", label: "联系过几次" },
        { holder: "textc", name: "QUESTION", label: "面临最大问题" },
        { holder: "textc", name: "INFO1G2", label: "配偶籍贯" },
        { holder: "textc", name: "INFO1G3", label: "配偶联系电话" },
        { holder: "textc", name: "INFO2", label: "父是否建在" },
        { holder: "textc", name: "INFO2G1", label: "父姓名" },
        { holder: "textc", name: "INFO2G2", label: "父年龄" },
        { holder: "textc", name: "INFO2G3", label: "父籍贯" },
        { holder: "textc", name: "INFO2G4", label: "父工作地" },
        { holder: "textc", name: "INFO2G5", label: "父居住地" },
        { holder: "textc", name: "INFO2G6", label: "父联系电话" },
        { holder: "textc", name: "INFO3", label: "母是否建在" },
        { holder: "textc", name: "INFO3G1", label: "母姓名" },
        { holder: "textc", name: "INFO3G2", label: "母年龄" },
        { holder: "textc", name: "INFO3G3", label: "母籍贯" },
        { holder: "textc", name: "INFO3G4", label: "母工作地" },
        { holder: "textc", name: "INFO3G5", label: "母居住地" },
        { holder: "textc", name: "INFO3G6", label: "母联系电话" },
        { holder: "textc", name: "INFO4G5", label: "子女居住地" },
        { holder: "textc", name: "INFO4G6", label: "子女联系电话" },
        { holder: "textc", name: "TEL", label: "电话" },
        { holder: "textc", name: "KZ1", label: "内外人员标识" },
        { holder: "textc", name: "SMOTHER_STATE", label: "配偶父親狀態" },
        { holder: "textc", name: "SFATHER_STATE", label: "配偶母親狀態" },
        { holder: "textc", name: "PERSON_COMPANY", label: "所属公司名称" },
        { holder: "textc", name: "PERSON_I_D_CARD", label: "身份证号" },
        { holder: "textc", name: "PERSON_COME_REASON", label: "来访事由" },
        { holder: "textc", name: "PERSON_KZ", label: "按要求佩戴口罩" },
        { holder: "textc", name: "PERSON_LEARN", label: "发文及相关规则" },
        { holder: "textc", name: "INFO4", label: "子女状况" },
        { holder: "textc", name: "INFO4G2", label: "子女出生年月" },
        { holder: "textc", name: "INFO4G3", label: "子女性别" },
        { holder: "textc", name: "INFO4G4", label: "子女学校或工作地" },
        { holder: "textc", name: "KZ2", label: "N95口罩及数量" },
        { holder: "textc", name: "KZ3", label: "其它口罩及数量" },
        { holder: "textc", name: "IS_F_RETIRE", label: "父亲是否退休" },
        { holder: "textc", name: "IS_M_RETIRE", label: "母亲是否退休" },
        { holder: "textc", name: "SPOUSE_NAME", label: "配偶姓名" },
        { holder: "textc", name: "SPOUSE_AGE", label: "配偶年龄" },
        { holder: "textc", name: "SPOUSE_NATIVE", label: "配偶籍贯" },
        { holder: "textc", name: "SPOUSE_ADDRESS", label: "配偶身份证地址" },
        { holder: "textc", name: "SPOUSE_WORK", label: "配偶工作情况" },
        { holder: "textc", name: "SPOUSEWORK_COMPANY", label: "配偶工作公司名称" },
        { holder: "textc", name: "SPOUSEWORK_ADDRESS", label: "配偶工作地址" },
        { holder: "textc", name: "SFATHER_NAME", label: "配偶父亲姓名" },
        { holder: "textc", name: "SFATHER_AGE", label: "配偶父亲年龄" },
        { holder: "textc", name: "SFATHER_ADDRESS", label: "配偶父亲居籍贯" },
        { holder: "textc", name: "SFATHER_WORK_PLACE", label: "配偶父亲工作地" },
        { holder: "textc", name: "SFATHER_LIVE_PLACE", label: "配偶父亲居住地" },
        { holder: "textc", name: "SFATHER_TEL", label: "配偶父亲电话" },
        { holder: "textc", name: "SIS_F_RETIRE", label: "配偶父亲是否退休" },
        { holder: "textc", name: "SMOTHER_NAME", label: "配偶母亲姓名" },
        { holder: "textc", name: "SMOTHER_AGE", label: "配偶母亲年龄" },
        { holder: "textc", name: "SMOTHER_ADDRESS", label: "配偶母亲地址" },
        { holder: "textc", name: "SMOTHER_WORK_PLACE", label: "配偶母亲工作地" },
        { holder: "textc", name: "SMOTHER_LIVE_PLACE", label: "配偶母亲居住地" },
        { holder: "textc", name: "SMOTHER_TEL", label: "配偶母亲电话" },
        { holder: "textc", name: "SIS_M_RETIRE", label: "配偶母亲是否退休" },
        { holder: "textc", name: "NAME5", label: "子女学习_工作情况" },
        { holder: "textc", name: "SEL_TIME", label: "行程日期" },
        { holder: "textc", name: "TI_WEN", label: "小区是否病例" },
        { holder: "textc", name: "AREA", label: "区域" },
        { holder: "textc", name: "LOC", label: "定位地址" },
        { holder: "textc", name: "LEAVE_DATE", label: "离厂时间" },
        { holder: "textc", name: "MODULE", label: "行程起始地点" },
        { holder: "textc", name: "ADCODE", label: "行程结束地址" },
        { holder: "textc", name: "TYPE", label: "类型" },
        { holder: "textc", name: "DWELL1", label: "居住所在地省" },
        { holder: "textc", name: "DWELL2", label: "居住所在地市" },
        { holder: "textc", name: "DWELL3", label: "居住所在地区" },
        { holder: "textc", name: "DWELL4", label: "地址" },
        { holder: "textc", name: "REDIO1", label: "居住房类型" },
        { holder: "textc", name: "REDIO1G", label: "其他" },
        { holder: "textc", name: "REDIO2", label: "地区是否为疫区" },
        { holder: "textc", name: "REDIO2G", label: "人数" },
        { holder: "textc", name: "REDIO3", label: "当日自己身体状况" },
        { holder: "textc", name: "REDIO3G", label: "当日自己身体说明" },
        { holder: "textc", name: "REDIO4", label: "当日测量体温" },
        { holder: "textc", name: "REDIO4G", label: "体温" },
        { holder: "textc", name: "REDIO5", label: "是否有外出" },
        { holder: "textc", name: "REDIO5G", label: "外出事项" },
        { holder: "textc", name: "REDIO5G1", label: "外出地点" },
        { holder: "textc", name: "REDIO5G2", label: "外出使用交通" },
        { holder: "textc", name: "REDIO6", label: "聚会情况" },
        { holder: "textc", name: "REDIO6G", label: "参加10人以上聚会" },
        { holder: "textc", name: "REDIO6G1", label: "聚会地点" },
        { holder: "textc", name: "REDIO6G2", label: "聚会类别" },
        { holder: "textc", name: "REDIO7", label: "接触湖北人员" },
        { holder: "textc", name: "REDIO7G", label: "接触湖北人员说明" },
        { holder: "textc", name: "REDIO8", label: "车辆借出情况" },
        { holder: "textc", name: "REDIO8G", label: "借出说明" },
        { holder: "textc", name: "REDIO9", label: "接触高风险人群" },
        { holder: "textc", name: "REDIO9G", label: "接触说明" },
        { holder: "textc", name: "REDIO10", label: "当日居住" },
        { holder: "textc", name: "REDIO10G", label: "当日居住说明" },
        { holder: "textc", name: "REDIO11", label: "接待来访亲友" },
        { holder: "textc", name: "REDIO11G", label: "亲友情况说明" },
        { holder: "textc", name: "REDIO12", label: "接触人群状态" },
        { holder: "textc", name: "REDIO12G", label: "接触人群情况说明" },
        { holder: "textc", name: "REDIO13", label: "当日用餐情况" },
        { holder: "textc", name: "REDIO13G", label: "用餐情况说明" },
        { holder: "textc", name: "D_AREA", label: "是否到过重点疫情区域" },
        { holder: "textc", name: "D_ISOLATE", label: "是否居家隔离" },
        { holder: "textc", name: "DISO_CLATE_DAY", label: "居家隔离天数" },
        { holder: "textc", name: "D_IS_INFECT", label: "小区病例情况" },
        { holder: "textc", name: "ADD_TIME", label: "新增时间" },
        { holder: "textc", name: "D_HIGH_PLACE", label: "到过以下高风险场所" },
        { holder: "textc", name: "D_WEAR_MASK", label: "是否戴口罩" },
        { holder: "textc", name: "BKZ1", label: "自有外科口罩数量" },
        { holder: "textc", name: "BKZ2", label: "N95口罩及数量" },
        { holder: "textc", name: "BKZ3", label: "其它口罩及数量" },
        { holder: "textc", name: "STORK_DYNAMIC", label: "与领导沟通过本人行程" },
        { holder: "textc", name: "D_HEALTH_FAMILY", label: "当日家人身体状况" },
        { holder: "textc", name: "D_AREA_STATUS", label: "出行期间所去区域" },
      ],
      values: {}
    },
    mateListLine: null,
    mateFormerLine: null
  },
}

const actions = {
  initList ({commit, state, rootState},data){
    // commit(TYPES.INIT_MAIN_LIST, data)
  }
}

const mutations = {
  [TYPES.INIT_MAIN_LIST] (state, data){
    console.log(data);
    console.log(state);
  }
}


export default {
  namespaced: true,
  state,
  mutations,
  actions
}
